# Generated by Django 2.2.2 on 2019-07-01 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_user', models.CharField(max_length=11, verbose_name='电话')),
                ('points', models.IntegerField(default=0, verbose_name='积分')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '积分列表',
                'verbose_name_plural': '积分列表',
            },
        ),
    ]
