# Generated by Django 2.2.2 on 2019-07-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_auto_20190708_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='修改时间'),
        ),
    ]
